### ISSUE TITLE
Dutch list

### ISSUE THREAD

**Issue by KevinDenys** [words/cmu-pronouncing-dictionary#2]
Is there a dutch CMU pronouncing dictionary?

**Comment by ArdentLemon** [comment]
> Is there a dutch CMU pronouncing dictionary?

There are a few public pages that have a lot of pronunciations; Wikitionary and Forvo so far seem to be the most promising if you're looking for pronunciation examples. I'm not sure if there are projects similar to the CMU dictionary in the Netherlands, but I feel like there should be something along those lines.

**Comment by zeke** [comment]
Let me know what you find!

**Comment by wooorm** [comment]
Closing this here, would be cool if there is a dutch list, but that can be its own project (which we can link to from here of course!)
